# Site settings
title: Jun Liu
description: 'Business Card Page'
url: 'http://chrisluu.github.io'
baseurl: ''
profilepic: '/images/junliu.jpeg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Jun Liu'
  email: jun.liu@cnu.edu.cn
#  twitter_username: 
#  facebook_username: joshgerdes
  github_username:  chrisluu
  linkedin_username:  dearchrisluu@gmail.com
#  meetup_name: 

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
